version: '1.0.{build}'
image: Visual Studio 2022
branches:
  only:
  - master
init:
  # Good practise, because Windows line endings are different from Unix/Linux ones
  - cmd: git config --global core.autocrlf true
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./ThunderED/ThunderED.csproj --verbosity m
build_script:
  # output will be in ./src/bin/debug/netcoreapp1.1/publish
  - cmd: dotnet publish ./ThunderED/ThunderED.csproj

artifacts:
 - path: '\ThunderED\bin\Debug\net6.0\publish'
   name: WebSite
clone_depth: 1
deploy: off
